// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2mlJh8W1MS9baAMogKX9GJMQlV67ULLY',
    appId: '1:35398336967:web:56f7689124410f2c8199e2',
    messagingSenderId: '35398336967',
    projectId: 'movie-app-b02ba',
    authDomain: 'movie-app-b02ba.firebaseapp.com',
    storageBucket: 'movie-app-b02ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3j3d_2GBqJKtPHaSjzCHhXWMdagItBXE',
    appId: '1:35398336967:android:06cc1c4d6f0d0a728199e2',
    messagingSenderId: '35398336967',
    projectId: 'movie-app-b02ba',
    storageBucket: 'movie-app-b02ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqlgzfQEWuznQPBiBeaX6j26S4mY4T7pE',
    appId: '1:35398336967:ios:53dacadf25d45c5f8199e2',
    messagingSenderId: '35398336967',
    projectId: 'movie-app-b02ba',
    storageBucket: 'movie-app-b02ba.appspot.com',
    iosClientId: '35398336967-3aqkc14gql34do13clgh31lell997dcf.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqlgzfQEWuznQPBiBeaX6j26S4mY4T7pE',
    appId: '1:35398336967:ios:9e09534547913d328199e2',
    messagingSenderId: '35398336967',
    projectId: 'movie-app-b02ba',
    storageBucket: 'movie-app-b02ba.appspot.com',
    iosClientId: '35398336967-auurdsk26qr8md8qte9lnju5s3o2cctk.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApp1.RunnerTests',
  );
}
